"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 18:26:38.729967
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_entries',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('namespace', sa.String(length=40), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('cache_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cache_entries_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cache_entries_namespace'), ['namespace'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_organization_id'), ['organization_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('parent_business_id', sa.Integer(), nullable=True),
    sa.Column('official_name', sa.String(length=255), nullable=False),
    sa.Column('name_variants', sa.JSON(), nullable=False),
    sa.Column('approved_name_variants', sa.JSON(), nullable=False),
    sa.Column('rejected_name_variants', sa.JSON(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('primary_category', sa.String(length=200), nullable=True),
    sa.Column('secondary_categories', sa.JSON(), nullable=False),
    sa.Column('business_type', sa.String(length=30), nullable=False),
    sa.Column('nap_name', sa.String(length=255), nullable=True),
    sa.Column('address_street', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('locality', sa.String(length=120), nullable=True),
    sa.Column('nap_province', sa.String(length=120), nullable=True),
    sa.Column('nap_country', sa.String(length=2), nullable=True),
    sa.Column('phone_primary', sa.String(length=40), nullable=True),
    sa.Column('phones_secondary', sa.JSON(), nullable=False),
    sa.Column('old_phones', sa.JSON(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('opening_hours', sa.String(length=500), nullable=True),
    sa.Column('hide_address', sa.Boolean(), nullable=False),
    sa.Column('service_area', sa.JSON(), nullable=False),
    sa.Column('google_maps_url', sa.String(length=1000), nullable=True),
    sa.Column('place_id', sa.String(length=255), nullable=True),
    sa.Column('gbp_url', sa.String(length=1000), nullable=True),
    sa.Column('gbp_location_name', sa.String(length=255), nullable=True),
    sa.Column('social_profiles', sa.JSON(), nullable=False),
    sa.Column('sector_directories', sa.JSON(), nullable=False),
    sa.Column('nap_confirmed', sa.Boolean(), nullable=False),
    sa.Column('nap_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('nap_confirmed_by', sa.Integer(), nullable=True),
    sa.Column('reference_notes', sa.Text(), nullable=True),
    sa.Column('audit_frequency', sa.String(length=20), nullable=False),
    sa.Column('audit_mode_default', sa.String(length=20), nullable=False),
    sa.Column('next_audit_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nap_confirmed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_organization_id'), ['organization_id'], unique=False)

    op.create_table('ai_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('tested_at', sa.DateTime(), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('mentions', sa.JSON(), nullable=False),
    sa.Column('cited_sources', sa.JSON(), nullable=False),
    sa.Column('errors_detected', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_tests_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_tests_organization_id'), ['organization_id'], unique=False)

    op.create_table('audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=80), nullable=True),
    sa.Column('completed_steps', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('nap_snapshot', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('schema_report', sa.JSON(), nullable=False),
    sa.Column('gbp_report', sa.JSON(), nullable=False),
    sa.Column('social_report', sa.JSON(), nullable=False),
    sa.Column('entity_graph', sa.JSON(), nullable=False),
    sa.Column('geo_report', sa.JSON(), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('log', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audits_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audits_organization_id'), ['organization_id'], unique=False)

    op.create_table('business_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=80), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_changes_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_changes_organization_id'), ['organization_id'], unique=False)

    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('cost_known', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_usage_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_provider'), ['provider'], unique=False)

    op.create_table('duplicate_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=255), nullable=False),
    sa.Column('members', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duplicate_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duplicate_groups_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duplicate_groups_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duplicate_groups_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_duplicate_groups_organization_id'), ['organization_id'], unique=False)

    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_queries_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_queries_organization_id'), ['organization_id'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('normalized_url', sa.String(length=2000), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('discovered_by', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('fetch_status', sa.String(length=30), nullable=False),
    sa.Column('fetch_detail', sa.Text(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('final_url', sa.String(length=2000), nullable=True),
    sa.Column('canonical', sa.String(length=2000), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('render_method', sa.String(length=20), nullable=True),
    sa.Column('extracted', sa.JSON(), nullable=False),
    sa.Column('extraction_methods', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=False),
    sa.Column('attribution', sa.JSON(), nullable=False),
    sa.Column('field_status', sa.JSON(), nullable=False),
    sa.Column('field_notes', sa.JSON(), nullable=False),
    sa.Column('overall_status', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=4), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('manual_status', sa.String(length=30), nullable=True),
    sa.Column('manual_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'normalized_url', name='uq_source_audit_url')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_organization_id'), ['organization_id'], unique=False)

    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.String(length=4), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('certainty', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('first_seen_audit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_actions_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_actions_business_id'))
        batch_op.drop_index(batch_op.f('ix_actions_audit_id'))

    op.drop_table('actions')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_organization_id'))
        batch_op.drop_index(batch_op.f('ix_sources_domain'))
        batch_op.drop_index(batch_op.f('ix_sources_audit_id'))

    op.drop_table('sources')
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_queries_organization_id'))
        batch_op.drop_index(batch_op.f('ix_search_queries_audit_id'))

    op.drop_table('search_queries')
    with op.batch_alter_table('duplicate_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duplicate_groups_organization_id'))
        batch_op.drop_index(batch_op.f('ix_duplicate_groups_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_duplicate_groups_business_id'))
        batch_op.drop_index(batch_op.f('ix_duplicate_groups_audit_id'))

    op.drop_table('duplicate_groups')
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_usage_provider'))
        batch_op.drop_index(batch_op.f('ix_api_usage_organization_id'))
        batch_op.drop_index(batch_op.f('ix_api_usage_created_at'))
        batch_op.drop_index(batch_op.f('ix_api_usage_audit_id'))

    op.drop_table('api_usage')
    with op.batch_alter_table('business_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_changes_organization_id'))
        batch_op.drop_index(batch_op.f('ix_business_changes_business_id'))

    op.drop_table('business_changes')
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audits_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audits_business_id'))

    op.drop_table('audits')
    with op.batch_alter_table('ai_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_tests_organization_id'))
        batch_op.drop_index(batch_op.f('ix_ai_tests_business_id'))

    op.drop_table('ai_tests')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_organization_id'))
        batch_op.drop_index(batch_op.f('ix_businesses_client_id'))

    op.drop_table('businesses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_organization_id'))

    op.drop_table('clients')
    op.drop_table('organizations')
    with op.batch_alter_table('cache_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cache_entries_namespace'))
        batch_op.drop_index(batch_op.f('ix_cache_entries_expires_at'))

    op.drop_table('cache_entries')
    # ### end Alembic commands ###
